on:
  push:
    tags:
      - "v*"
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: zip files
      run: |
        rm -rf ./.git ./.gitignore ./.github
        zip zapsCoolPhotonTheme.xpi *
        
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
            zapsCoolPhotonTheme.xpi
