on:
  push:
    tags:
      - "v*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: sync zcpt
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          repository: zapsnh/zapsCoolPhotonTheme
          ref: webextension
          path: chrome

    - name: push zcpt
      run : |
        git add .
        git commit -m "sync zcpt"
        git push origin HEAD:main

    - name: bump version
      run: |
        python3 .github/workflows/bump_ver.py bump ${{ github.ref_name }}    

    - name: commit and push changes
      run: |
        git add .
        git commit -m "bump version: ${{ github.ref_name }}"
        git push origin HEAD:main

    - name: zip files
      run: |
        rm -rf ./README.md ./.git ./.gitignore ./.github ./updates.json
        zip -r -FS zapsCoolPhotonTheme.xpi *
        
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
            zapsCoolPhotonTheme.xpi
