on:
  push:
    tags:
      - "v*"

jobs:
  bump-ver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
  
    - name: bump version
      run: |
        python3 .github/workflows/bump_ver.py bump ${{ github.ref_name }}    

    - name: commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "bump version: ${{ github.ref_name }}"
        git push origin HEAD:main

  package:
    runs-on: ubuntu-latest
    needs: bump-ver
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: zip files
      run: |
        rm -rf ./README.md ./.git ./.gitignore ./.github ./updates.json
        zip -r -FS zapsCoolPhotonTheme.xpi *
        
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
            zapsCoolPhotonTheme.xpi
