on:
  push:
    tags:
      - "v*"

jobs:
  package:
    strategy:
      matrix:
        include:
          - name: "zapsCoolPhotonTheme"
            branch: "HEAD:main"
            sync-branch: "webextension"
          - name: "zapsCoolPhotonTheme-esr"
            branch: "HEAD:esr"
            sync-branch: "webextension-esr"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: sync zcpt
      uses: actions/checkout@v4
      with:
          repository: zapsnh/zapsCoolPhotonTheme
          ref: ${{ matrix.sync-branch }}
          path: chrome

    - name: add gh bot creds
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: bump version
      if: matrix.name == 'zapsCoolPhotonTheme'
      run: |
        python3 .github/workflows/bump_ver.py bump ${{ github.ref_name }}

    - name: bump version - ESR
      if: matrix.name == 'zapsCoolPhotonTheme-esr'
      run: |
        python3 .github/workflows/bump_ver.py bumpESR ${{ github.ref_name }}

    - name: commit and push changes
      run: |
        git add .
        git commit -m "bump version: ${{ github.ref_name }}"
        git push origin ${{ matrix.branch }} --force

    - name: zip files
      run: |
        rm -rf ./README.md ./.git ./.gitignore ./.github ./updates.json ./chrome/.git ./chrome/.github ./ESR_VERSION ./chrome/theme.json ./chrome/preferences.json
        zip -r -FS ${{ matrix.name }}.xpi *
        
    - name: release
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
          ${{ matrix.name }}.xpi
