on:
  push:
    tags:
      - "v*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: sync zcpt
      uses: actions/checkout@v3
      with:
          repository: zapsnh/zapsCoolPhotonTheme
          ref: webextension
          path: chrome

    - name: add gh bot creds
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: bump version
      run: |
        python3 .github/workflows/bump_ver.py bump ${{ github.ref_name }}    

    - name: commit and push changes
      run: |
        git add .
        git commit -m "bump version: ${{ github.ref_name }}"
        git push origin HEAD:main

    - name: zip files
      run: |
        rm -rf ./README.md ./.git ./.gitignore ./.github ./updates.json ./chrome/.git
        zip -r -FS zapsCoolPhotonTheme.xpi *
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: add gh bot creds
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: sync zcpt - ESR
      uses: actions/checkout@v3
      with:
          repository: zapsnh/zapsCoolPhotonTheme
          ref: webextension-esr
          path: chrome

    - name: commit and push changes - ESR
      run: |
        git add .
        git commit -m "bump version: ${{ github.ref_name }}"
        git push origin HEAD:esr

    - name: zip files - ESR
      run: |
        rm -rf ./README.md ./.git ./.gitignore ./.github ./updates.json ./chrome/.git
        zip -r -FS zapsCoolPhotonTheme-esr.xpi *
        
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
            zapsCoolPhotonTheme.xpi
            zapsCoolPhotonTheme-esr.xpi
