on:
  push:
    tags:
      - "v*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: sync zcpt
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          repository: zapsnh/zapsCoolPhotonTheme
          ref: webextension
          path: chrome

    - name: check if there are any changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: chrome/**
        files_ignore: chrome/.git
    
    - name: push zcpt
      if: steps.changed-files.outputs.any_changed == 'true'
      run : |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "sync zcpt"
        git push origin HEAD:main

    - name: bump version
      run: |
        python3 .github/workflows/bump_ver.py bump ${{ github.ref_name }}    

    - name: commit and push changes
      run: |
        git add .
        git commit -m "bump version: ${{ github.ref_name }}"
        git push origin HEAD:main

    - name: zip files
      run: |
        rm -rf ./README.md ./.git ./.gitignore ./.github ./updates.json ./chrome/.git
        zip -r -FS zapsCoolPhotonTheme.xpi *
        
    - name: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: |
            zapsCoolPhotonTheme.xpi
